### ISSUE TITLE
RSS Feeds can't refresh

### ISSUE THREAD

**Issue by Fleischpirat** [khawkins98/facebook-json-to-rss#1]
Hi,
in a few feeds there are some problems by update the feeds. Could you please help me?

Here are some examples of the facebook pages and my script:
xxx

And is there any chance that you implement the possebility to get pictures in the feed?

Kind regards

**Comment by khawkins98** [comment]
Hi @Fleischpirat 

I've made a few fixes and added support for the facebook thumbnail images (note that they're only 130px x 130px).

Shout if you're still seeing errors.

**Comment by Fleischpirat** [comment]
Hi @khawkins98 
thank you very much for your time!
The changes works great.

I've only one feed that don't work in my Newsreader. But this problem could also come from there:
xxx

Thank you again!

**Comment by khawkins98** [comment]
Hrm, using 8859-1 encoding hasn't helped with umlauts as much as I had hopped. So I've just CDATA'd the link tag as well. 

Seems to parse well now.

**Comment by Fleischpirat** [comment]
Hi @khawkins98 
that works :-)
thank you so much for your help!
